title: Adrian Huber
description: Personal website and blog
url: https://adrian-huber.org
baseurl: ""

# GitHub Pages automatically sets the following
markdown: kramdown
lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Add excerpt separator
excerpt_separator: <!--more-->

# Collections
collections:
  posts:
    output: true
    permalink: /writing/:title/
  research:
    output: true
    permalink: /research/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Default layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "_posts"
    values:
      layout: post
  -
    scope:
      path: "_research"
    values:
      layout: research
  -
    scope:
      path: "_projects"
    values:
      layout: project